object Versions {
    const val kotlin = "1.8.0"
    const val agp = "7.4.2"

    const val composeKotlinCompiler = "1.4.1"
    const val composeBomVersion = "2023.01.00"
    const val composeActivities = "1.6.1"
    const val composeViewModels = "2.5.1"

    const val coroutines = "1.6.4"
    const val ktor = "2.2.3"
    const val serialization = "1.5.0"
    const val dateTime = "0.4.0"
    const val navigation = "2.5.3"
    const val sqlDelight = "2.0.0-alpha05"
    const val kodein = "7.17.0"
    const val mokoMvvm = "0.15.0"
    const val orbitMvi = "4.6.1"
    const val kswift = "0.6.1"
    const val junit = "4.13.2"
    const val mockk = "1.13.4"
    const val napier = "2.6.1"
    const val libres = "1.1.6"
    const val okio = "3.3.0"
    const val coil = "2.2.2"
}